import {type Metadata} from 'next';
import {GeistSans} from 'geist/font/sans';
import '~/styles/globals.css';
import {TRPCReactProvider} from '~/trpc/react';
import Header from '@/header';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{rel: 'icon', url: '/favicon.ico'}],
};

export default function RootLayout({
  children,
}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang='en' className={`${GeistSans.variable}`}>
      <body className=''>
        <Header />
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
